In [ ]:
import numpy as np

In [4]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [9]:
b=np.array([[6.0,7.0,8.0],[5.0,4.0,3.0]])
print(b)

[[6. 7. 8.]
 [5. 4. 3.]]


In [10]:
#Get Dimension
a.ndim
b.ndim

2

In [11]:
#Get Shape
b.shape

(2, 3)

In [12]:
#Get Type
a.dtype
b.dtype

dtype('float64')

In [13]:
a.itemsize

8

In [14]:
b.size

6

In [15]:
a.nbytes

24

In [16]:
b.itemsize

8

Accessing/Changing specific elements,rows,columns

In [18]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [20]:
#Get a Specific element
a[1,2]

8

In [21]:
#Get a Specific row
a[0,:]

array([1, 2, 3, 4, 5])

In [22]:
##Get a Specific column
a[:,2]

array([3, 8])

In [23]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:-1:2]

array([2, 4])

In [25]:
a[1,2]=20
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5]
 [ 6  7  2  9 10]]


In [33]:
b = np.array([[[1, 2], [3,4]],[[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [35]:
#Get a Specific element
b[0,1,1]

4

In [36]:
#All zero matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [40]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [42]:
np.zeros((2,3,3,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [43]:
#All 1s matrix
np.ones((4,4,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [44]:
#Any other Number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [45]:
np.full((2,2,3),99)

array([[[99, 99, 99],
        [99, 99, 99]],

       [[99, 99, 99],
        [99, 99, 99]]])

In [48]:
#Any other Number
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(np.full_like(a, 100))

[[100 100 100 100 100]
 [100 100 100 100 100]]


In [49]:
#Random decimal number
np.random.rand(4,2)

array([[0.83840212, 0.38292356],
       [0.41840877, 0.96944034],
       [0.48485687, 0.45471235],
       [0.10338867, 0.19684372]])

In [50]:
#Random integer number
np.random.randint(7,size=(3,3))

array([[3, 5, 5],
       [6, 2, 2],
       [4, 0, 2]])

In [51]:
np.random.randint(1000,size=(9,6))

array([[942, 914, 914, 477, 500, 730],
       [670, 984,  55, 296, 624, 347],
       [587, 524, 702, 132, 449, 329],
       [421, 719, 910, 340, 543,  56],
       [553, 287, 654, 770, 743,  51],
       [796,  96, 558, 440, 343, 347],
       [105, 500, 767, 680, 496, 355],
       [500, 497, 461, 742, 931, 909],
       [745,  35, 773, 836, 681, 898]])

In [52]:
np.random.randint(-1000,1000,size=(9,6))

array([[ 816, -919,  123, -560, -899,   -7],
       [ -39,  613, -577, -313,  -59, -864],
       [-472,   99,  979, -979, -967,  778],
       [ -37,  954,  332,  774,  588,  -34],
       [ -48,  367,  177, -595,  875,  108],
       [-765,  661,  818, -872,  817, -572],
       [ 273,  855,  829,  327,  714, -645],
       [ 704,  710, -840,  769,  837,  902],
       [-559, -388, -299, -950,  258, -180]])

In [55]:
#Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
#Repeat Array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [59]:
arr=np.array([[[9,9,9]]])
r2=np.repeat(arr,5,axis=1)
print(r2)

[[[9 9 9]
  [9 9 9]
  [9 9 9]
  [9 9 9]
  [9 9 9]]]


In [62]:
output = np.zeros((7,7))
z = np.ones((5, 5))
z[2, 2] = 5
output[1:-1, 1:-1] = z
print(output)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [63]:
output = np.zeros((5,5))
print(output)
z = np.ones((3,3))
z[2, 2] = 5
print(z)
output[1:-1, 1:-1] = z
print(output)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 5.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 5. 0.]
 [0. 0. 0. 0. 0.]]


In [65]:
a = np.array([1, 2, 3, 4, 5])
b = a
b[2] = 20
print(a)

[ 1  2 20  4  5]


Mathematics

In [67]:
a = np.array(([1, 2, 3, 4, 5]))
print(a)

[1 2 3 4 5]


In [70]:
a+2

array([3, 4, 5, 6, 7])

In [71]:
a-2

array([-1,  0,  1,  2,  3])

In [72]:
a*2

array([ 2,  4,  6,  8, 10])

In [73]:
a%2

array([1, 0, 1, 0, 1])

In [74]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [75]:
a^2

array([3, 0, 1, 6, 7])

In [76]:
b = np.array(([6, 7, 8, 9, 10]))
a+b

array([ 7,  9, 11, 13, 15])

In [77]:
a/b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [79]:
a*b

array([ 6, 14, 24, 36, 50])

In [80]:
#Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

Linear Algebra

In [86]:
z = np.ones((5, 5))
print(z)
y=np.full((3,2),2)
print(y)
np.matmul(a,b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


130

In [87]:
#Find Determinant
c=np.identity(3)
np.linalg.det(c)

1.0

Statistics

In [89]:
stats= np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
print(stats)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [90]:
np.min(stats)

1

In [91]:
np.max(stats)

10

In [92]:
np.max(stats,axis=1)

array([ 5, 10])

In [93]:
np.sum(stats,axis=0)

array([ 7,  9, 11, 13, 15])

In [94]:
a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
b = np.max(a, axis=1).sum()
print(b)

15


Reorganizing Array

In [98]:
before = np.array(([1, 2, 3, 4], [5,6, 7, 8]))
print (before)
after = before.reshape((4,2))
print (after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [100]:
#Horizontal stack
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [101]:
# Vertical stack
h1=np.array([1,2,3,4])
h2=np.array([5,6,7,8])

np.hstack([v1,v2,v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

Miscellaneous

In [102]:
filedata = np.genfromtxt('data.txt', delimiter=',')
output = filedata[filedata < 50]
print(output)

OSError: data.txt not found.