In [10]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [11]:
weights = [w1, w2, w3]

In [19]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [20]:
crop_yield(kanto, weights)

56.8

In [21]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [22]:
kanto_yield_apples = kanto_temp * w1 + kanto_rainfall * w2 + kanto_humidity * w3
kanto_yield_apples

56.8

In [23]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [24]:
print("The expected yield of apples in Kanto region is {} tons per hectare.".format(kanto_yield_apples))

The expected yield of apples in Kanto region is 56.8 tons per hectare.


In [25]:
def crop_yield(region, weights):
    result=0
    for x,w in zip(region, weights):
        result+= x*w
    return result

In [26]:
crop_yield(kanto, weights)

56.8

In [27]:
crop_yield(johto, weights)

76.9

In [28]:
crop_yield(unova, weights)

74.9

In [29]:
#Going from Python lists to Numpy arrays

In [30]:
import numpy as np

In [31]:
#We can now use the np.array function to create Numpy arrays.
kanto= np.array([73,67,43])

In [32]:
kanto

array([73, 67, 43])

In [33]:
weights=np.array([w1,w2,w3])

In [34]:
weights

array([0.3, 0.2, 0.5])

In [37]:
#Numpy arrays have the type ndarray
type(kanto)

numpy.ndarray

In [38]:
type(weights)

numpy.ndarray

In [39]:
 #Numpy arrays support the indexing notation []
weights[0]

0.3

In [40]:
kanto[2]

43

In [41]:
#Operating on Numpy arrays
##We can now compute the dot product of the two vectors using the np.dot function.
np.dot(kanto,weights)

56.8

In [42]:
#We can achieve the same result with low-level operations supported by Numpy arrays: performing an element-wise multiplication and calculating the resulting numbers' sum.
(kanto * weights).sum()

56.8

In [45]:
#The * operator performs an element-wise multiplication of two arrays if they have the same size. The sum method calculates the sum of numbers in an array.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr1*arr2

array([ 4, 10, 18])

In [46]:
arr2.sum()

15

In [47]:
#Benefits of using Numpy arrays
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)


In [48]:
%%time
result =0
for x1,x2 in zip(arr1,arr2):
    result += x1*x2
result

CPU times: user 156 ms, sys: 2.61 ms, total: 159 ms
Wall time: 158 ms


833332333333500000

In [49]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: user 3.82 ms, sys: 2.46 ms, total: 6.28 ms
Wall time: 2.97 ms


833332333333500000

In [50]:
#Multi-dimensional Numpy arrays

In [51]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

In [52]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [53]:
# 2D array (matrix)
climate_data.shape

(5, 3)

In [54]:
weights

array([0.3, 0.2, 0.5])

In [55]:
# 1D array (vector)
weights.shape

(3,)

In [56]:
# 3D array 
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])

In [57]:
#Numpy arrays can have any number of dimensions and different lengths along each dimension. We can inspect the length along each dimension using the .shape property of an array.
arr3.shape

(2, 2, 3)

In [58]:

#All the elements in a numpy array have the same data type. You can check the data type of an array using the .dtype property.

weights.dtype

dtype('float64')

In [59]:
climate_data.dtype

dtype('int64')

In [60]:
#If an array contains even a single floating point number, all the other elements are also converted to floats.
arr3.dtype

dtype('float64')

In [61]:
#We can use the np.matmul function or the @ operator to perform matrix multiplication.
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [62]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [64]:
import urllib.request
urllib.request.urlretrieve('https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 'climate.txt')

URLError: <urlopen error [Errno 60] Operation timed out>

In [67]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

OSError: climate.txt not found.

In [66]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [75]:
climate_data.shape

(5, 3)

In [76]:
weights = np.array([0.3, 0.2, 0.5])

In [77]:
np.savetxt('climate_results.txt', 
           climate_results, 
           fmt='%.2f', 
           delimiter=',',
           header='temperature,rainfall,humidity,yeild_apples', 
           comments='')

NameError: name 'climate_results' is not defined

In [78]:
climate_results

NameError: name 'climate_results' is not defined

In [79]:
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)

ValueError: cannot reshape array of size 5 into shape (10000,1)

In [80]:
yields = climate_data @ weights

In [81]:
yields

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [82]:
yields.shape

(5,)

In [83]:
#Arithmetic operations, broadcasting and comparison
arr2= np.array([[1,2,3,4],
                [5,6,7,8],
                [9,1,2,3]])


In [84]:
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [85]:
# Adding a scalar
arr2 + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [86]:
# Element-wise subtraction
arr3 - arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [88]:
#Division by scalar
arr2/2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [89]:
#Element-wise multiplication
arr2*arr3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [90]:
# Modulus with scalar
arr2 % 4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]])

In [91]:
#Array Broadcasting
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [92]:
arr2.shape

(3, 4)

In [93]:
arr4 = np.array([4, 5, 6, 7])

In [94]:
arr4.shape

(4,)

In [95]:
arr2 + arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [96]:
arr5 = np.array([7, 8])

In [97]:
arr5.shape

(2,)

In [98]:
arr2 + arr5

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

In [99]:
#Array Comparison
##Numpy arrays also support comparison operations like ==, !=, > etc. The result is an array of booleans.
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [100]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [101]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True, False]])

In [102]:
arr1 >= arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [103]:
arr1 < arr2

array([[ True, False, False],
       [False, False, False]])

In [104]:
(arr1 == arr2).sum()

3

In [105]:
#Array indexing and slicing

In [106]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [107]:
arr3.shape

(3, 2, 4)

In [108]:
# Single element
arr3[1, 1, 2]

36.0

In [109]:
# Subarray using ranges
arr3[1:, 0:1, :2]

array([[[15., 16.]],

       [[98., 32.]]])

In [110]:
# Mixing indices and ranges
arr3[1:, 1, 3]

array([18., 43.])

In [111]:
# Using fewer indices
arr3[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [112]:
# Using fewer indices
arr3[:2, 1]

array([[13., 14., 15., 19.],
       [63., 92., 36., 18.]])

In [113]:
# Using too many indices
arr3[1,3,2,1]

IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

In [114]:
#Other ways of creating Numpy arrays
# All zeros
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [115]:
# All ones
np.ones([2, 2, 3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [116]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [117]:
# Random vector
np.random.rand(5)

array([0.6912418 , 0.06310288, 0.5486208 , 0.62485759, 0.7249882 ])

In [118]:
# Fixed value
np.full([2, 3], 42)

array([[42, 42, 42],
       [42, 42, 42]])

In [119]:
# Range with start, end and step
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [120]:
# Equally spaced numbers in a range
np.linspace(3, 27, 9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])