In [144]:
import numpy as np
import sys

In [2]:
n=3

In [3]:
2**3

8

In [4]:
120

120

In [5]:
2**32

4294967296

In [6]:
#want to create a number 8bit like this
np.int8

numpy.int8

In [7]:
np.int64  

numpy.int64

Basic Numpy Arrays

In [9]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [10]:
a = np.array([1, 2, 3, 4])

In [11]:
b = np.array([0, .5, 1, 1.5, 2])

In [12]:
a[0], a[1]

(1, 2)

In [13]:
a[0:]

array([1, 2, 3, 4])

In [14]:
a[1:3]

array([2, 3])

In [15]:
a[1:-1]

array([2, 3])

In [16]:
a[::2]

array([1, 3])

In [17]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [18]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [19]:
b[[0, 2, -1]]

array([0., 1., 2.])

Dimensions and shapes

In [20]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [21]:
A.shape

(2, 3)

In [22]:
A.ndim

2

In [23]:
A.size

6

In [24]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [25]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [26]:
B.shape

(2, 2, 3)

In [27]:
B.ndim

3

In [28]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [115]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

/var/folders/r6/zl0bpg_s1k968v51vt4cqjf80000gn/T/ipykernel_2912/548599459.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [30]:
C.dtype

dtype('O')

In [31]:
C.shape

(2,)

In [ ]:
C.size

In [ ]:
type(C[0])

Indexing and Slicing of Matrices

In [32]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [33]:
A[1]

array([4, 5, 6])

In [34]:
A[1][0]

4

In [35]:
# A[d1, d2, d3, d4]

In [36]:
A[1, 0]

4

In [37]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [39]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [40]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
A[1] = np.array([10, 10, 10])

In [42]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [43]:
A[2] = 99

In [44]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

Summary statistics

In [53]:
a = np.array([1, 2, 3, 4])

In [54]:
a.sum()

10

In [55]:
a.mean()

2.5

In [56]:
a.std()

1.118033988749895

In [57]:
a.var()

1.25

In [58]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [59]:
A.sum()

45

In [60]:
A.mean()

5.0

In [61]:
A.std()

2.581988897471611

In [62]:
A.sum(axis=0)

array([12, 15, 18])

In [63]:
A.sum(axis=1)

array([ 6, 15, 24])

In [64]:
A.mean(axis=0)

array([4., 5., 6.])

In [65]:
A.mean(axis=1)

array([2., 5., 8.])

In [66]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [67]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

Broadcasting and Vectorized operations

In [68]:
a = np.arange(4)

In [69]:
a

array([0, 1, 2, 3])

In [70]:
a + 10

array([10, 11, 12, 13])

In [71]:
a * 10

array([ 0, 10, 20, 30])

In [72]:
a

array([0, 1, 2, 3])

In [73]:
a += 100

In [74]:
a

array([100, 101, 102, 103])

In [75]:
l = [0, 1, 2, 3]

In [76]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [77]:
a = np.arange(4)

In [78]:
a

array([0, 1, 2, 3])

In [79]:
b = np.array([10, 10, 10, 10])

In [80]:
b

array([10, 10, 10, 10])

In [81]:
a + b

array([10, 11, 12, 13])

In [82]:
a * b

array([ 0, 10, 20, 30])

Boolean arrays
(Also called masks)

In [83]:
a = np.arange(4)

In [84]:
a

array([0, 1, 2, 3])

In [85]:
a[0], a[-1]

(0, 3)

In [86]:
a[[0, -1]]

array([0, 3])

In [87]:
a[[True, False, False, True]]

array([0, 3])

In [88]:
a

array([0, 1, 2, 3])

In [89]:
a >= 2

array([False, False,  True,  True])

In [90]:
a[a >= 2]

array([2, 3])

In [91]:
a.mean()

1.5

In [92]:
a[a > a.mean()]

array([2, 3])

In [93]:
a[~(a > a.mean())]

array([0, 1])

In [94]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [95]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [96]:
A = np.random.randint(100, size=(3, 3))

In [97]:
A

array([[13, 86, 97],
       [97, 94, 17],
       [59, 85,  1]])

In [98]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([13, 97, 94, 59,  1])

In [99]:
A > 30

array([[False,  True,  True],
       [ True,  True, False],
       [ True,  True, False]])

In [100]:
A[A > 30]

array([86, 97, 97, 94, 59, 85])

Linear Algebra

In [101]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [102]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [103]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [104]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [105]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [106]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

Size of objects in Memory
Int, floats

In [145]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [146]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [118]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [119]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [120]:
np.dtype(float).itemsize

8

Lists are even larger

In [147]:
# A one-element list
sys.getsizeof([1])

64

In [148]:
# An array of one element in numpy
np.array([1]).nbytes

8

And performance is also important

In [149]:
l = list(range(100000))

In [150]:
a = np.arange(100000)

In [151]:
%time np.sum(a ** 2)

CPU times: user 1.3 ms, sys: 352 µs, total: 1.65 ms
Wall time: 1.19 ms


333328333350000

In [152]:
%time sum([x ** 2 for x in l])

CPU times: user 42 ms, sys: 3.33 ms, total: 45.3 ms
Wall time: 43.5 ms


333328333350000

Useful Numpy functions

In [153]:
#random

In [154]:
np.random.random(size=2)

array([0.52057758, 0.51440219])

In [155]:
np.random.normal(size=2)

array([ 0.01770162, -0.86937493])

In [156]:
np.random.rand(2, 4)

array([[0.5136357 , 0.30286506, 0.29186616, 0.02015473],
       [0.14824652, 0.51919121, 0.14801719, 0.27924219]])

In [157]:
#arrange

In [158]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [159]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [160]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [161]:
#reshape

In [162]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [163]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [164]:
#linspace

In [165]:
np.linspace(0, 1, 5)
np.linspace(0, 1, 20)
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [166]:
#zeros, ones, empty

In [167]:
np.zeros(5)
np.zeros((3, 3))
np.ones(5)
np.ones((3, 3))
np.empty(5)
np.empty((2, 2))

array([[0.e+000, 5.e-324],
       [0.e+000, 5.e-324]])

In [168]:
#identity and eye

In [169]:
np.identity(3)
np.eye(3, 3)
np.eye(8, 4)
np.eye(8, 4, k=1)
np.eye(8, 4, k=-3)
"Hello World"[6]

'W'